### ISSUE TITLE
Batch OCR

### ISSUE THREAD

**Issue by dlivinglabs** [schlundd/obsidian-ocr-plugin#1]
is there a way to do it with the local tessaract installation?

**Comment by schlundd** [comment]
This plugin does not interact with a local tesseract installation, but presents an alternative. The OCR happens remotely (and not with tesseract).

If you want to use a local tesseract installation, maybe the people in the forum can help: https://forum.obsidian.md/t/basic-ocr-in-obsidian/18087/20

If you actually do want to use this plugin for batch processing, can you describe your usecase a bit more detailed?
