### ISSUE TITLE
Excalidraw error with this image - receiving status 413

### ISSUE THREAD

**Issue by zsviczian** [schlundd/obsidian-ocr-plugin#11]
[base64image.zip](https://github.com/schlundd/obsidian-ocr-plugin/files/10049315/base64image.zip)

![image](https://user-images.githubusercontent.com/14358394/202895662-f9e474f1-2c0c-4761-a9d2-e624466a8211.png)

**Comment by schlundd** [comment]
For documentation purposes: Max file size was to low. Fixed since november.
