### ISSUE TITLE
Support for recognising latex

### ISSUE THREAD

**Issue by Zabooby** [schlundd/obsidian-ocr-plugin#12]
Are there any plans to add latex recognition to the plugin? It would basically be adding [mathpix ](https://mathpix.com/)to obsidian which would be super useful to users that work with maths formulas regularly (there's a lot of us)!

There are a [bunch ](https://github.com/search?q=latex+ocr)of projects on GitHub that do this, would be possible to add this functionality to your plugin?

**Comment by Zabooby** [comment]
Input: 
![image](https://github.com/schlundd/obsidian-ocr-plugin/assets/78969986/04dcd89e-f953-4dbe-8aca-41c4ddaf6c2b)
Output (Source mode in Obsidian):
![image](https://github.com/schlundd/obsidian-ocr-plugin/assets/78969986/6d739758-4460-46de-bdcb-822c6cdc7d25)
How it's displayed:
![image](https://github.com/schlundd/obsidian-ocr-plugin/assets/78969986/bac8efdd-a3ae-41d9-8464-e39c07208318)

**Comment by schlundd** [comment]
Thank you. I'll check some options.

**Comment by schlundd** [comment]
Could you please test this? Go to the Taskbone plugin settings and use the import command feature to import:

`https://app.taskbone.com/assets/commands/OCRMathImageAndInsertAtCursorPosition.json`

You will then have a command "OCR Math image and insert at cursor position"

Unfortunately, there seems to be no good option that would allow me to add this for free. After the testing phase, I will have to attach some pricing to this feature.

**Comment by Zabooby** [comment]
Wow it works great, just how I imagined it! It's unfortunate that it can't be done for free. 

What are you currently using for ocr for latex, were you not able to find any viable options from the link in my original post?

**Comment by schlundd** [comment]
I honestly didn't invest a lot of time to check all options, so I am just using the MathPix API in the backend. This is not very cheap though. So I need to either allow you to enter your own MathPix credentials or charge for it. Feel free to just use the command in the meantime. Maybe just don't abuse it, please. :-)

**Comment by Zabooby** [comment]
Luckily (for you) uni hasn't started yet so I won't be needing it right now. Thanks for implementing this feature though, it will definitely help speed up my note taking. 

Down the line would you be interested in testing alternatives or are you happy with the current implementation?

**Comment by schlundd** [comment]
I'd say, I am happy for now. That may change depending on usage and feedback.
