### ISSUE TITLE
[Feature Request] Add the ability to use common language dates for Todoist tasks

### ISSUE THREAD

**Issue by dm7500** [schlundd/obsidian-ocr-plugin#13]
Todoist supports use of common language dates (today, next monday, etc) for due dates. Entering a task in Obsidian like below would make workflows much easier

```
- [ ] Check on status of indexer #due::today
```

**Comment by schlundd** [comment]
Sorry, for the late reply. In case it is still relevat for you: You can configure this on your own. Open the Taskbone Plugin settings and the configuration of the sync command. Update the value of "dueDate" to 

`{{ task | findOne: '(?<=(#due::|📅 )).*?(?= ?($|#))' }}`

Scroll down and save. You can now use any text that Todoist accepts.
