### ISSUE TITLE
Choose a specific OCR image folder

### ISSUE THREAD

**Issue by Taitava** [schlundd/obsidian-ocr-plugin#2]
Hi,

when I run the `Taskbone OCR: Create annotation page for image` command, it scaffolds a list of all images in my vault (except those that already have an annotation file next to them) and asks me to pick the image that I want. However, I'd like to be able to define a folder in the plugin's settings - say *Images/Unprocessed* - that would be the only place where this plugin would pick images for the OCR process.

The reason for this is that once the annotation file is created, I will rename the file with a completely different name, or copy small parts of the annotation text to other files and delete the annotation file. When I rename/delete the annotation file, the plugin will not anymore know that this particular image is already annotated. That's why I'd like to put new images into a folder named *Unprocessed*, and after the annotation is done, I will manually move the images to somewhere else.

Another reason is that in some cases I might want to have images that I never want to annotate.

Thanks! And it's a nice plugin! :)

**Comment by schlundd** [comment]
Thanks for the detailed explanation. This sounds like a reasonable use case and should not be very hard to implement. I'll lool into it.

**Comment by schlundd** [comment]
Ok, it took a while... This is finally possible, by using the "new" Taskbone Plugin www.taskbone.com. This is way more flexible to configure, but maybe not straight forward. Check out https://docs.taskbone.com/updates/2022-05-27-ocr-and-new-output-options and let me know, how _exactly_ you want it to behave, so I can support with your configuration.

The feature will be backported into this plugin, but there is no timeline.

**Comment by Taitava** [comment]
> Check out https://docs.taskbone.com/updates/2022-05-27-ocr-and-new-output-options and let me know, how _exactly_ you want it to behave, so I can support with your configuration.

Sorry, I did not quite understand this. I think the documentation is about configuring **output** options, but my suggestion was to be able to select an "input" folder, i.e. folder where to pick images, and ignore images in all other folders.

Anyway, the ability to select where the annotation text goes, is a nice thing, even if I don't see a relation with this particular issue. 😎

**Comment by schlundd** [comment]
Finally generally available with 2.0.0. 

Just in case, this is still relevant and for documentation purposes:

In the plugin settings, open the configuration of the corresponding command. You are able to configure a regular expression to filter which files should be in the suggestion list, when you run the command.

![Selection_271](https://github.com/schlundd/obsidian-ocr-plugin/assets/1160643/ed1699bb-f35f-437f-b9e4-b4796a2a928f)

Assuming you have a directory called `unprocessed` you could change it to something like

`unprocessed.*\.(png|jpg|jpeg|gif)$`

Don't forget to scroll to the bottom and save.
