### ISSUE TITLE
400 Error

### ISSUE THREAD

**Issue by leepotts** [schlundd/obsidian-ocr-plugin#5]
Whenever I try to use this plugin I get this error no matter what image file I try to use. Any idea how to fix this? Is it an API thing?
![image](https://user-images.githubusercontent.com/4944774/158030412-a2295dc6-da8a-4d6a-b35b-6f9bd48d9cc1.png)

**Comment by prdlik007** [comment]
The same to me.

**Comment by schlundd** [comment]
The issue is resolved and the plugin works again.

**Comment by leepotts** [comment]
Thank you!
