### ISSUE TITLE
Adding a built-in local option for OCR via Tesseract-wasm

### ISSUE THREAD

**Issue by niposch** [schlundd/obsidian-ocr-plugin#8]
There is an interesting project that builds tesseract to run on wasm/js. => https://github.com/robertknight/tesseract-wasm
A demo is available here: https://robertknight.github.io/tesseract-wasm/

I was wondering whether this would be a possible addition to this plugin.
It would allow for local processing of images while also offering a simple install option via the obsidian community plugins tab.
It prevents issues with API rate limits and therefore would allow for bulk conversion of images (transcribe all images in vault). Additionally, it would allow offline usage of the plugin.
The feature could be made available as an optional toggle.

**Comment by schlundd** [comment]
The plugin only works with the corresponding online service. It is not planned to change that.
